name: 'Publish Maven Artifact'
description:
  'This action publishes a maven artifact from a local maven repository to a
  remote repository.'
author: 'Team AppliedEnergistics'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'purple'

# Define your inputs here.
inputs:
  local-repository-path:
    description: 'The path to the local Maven repository to publish from'
    required: true
  remote-repository-url:
    description: 'The URL to the remote Maven repository'
    required: true
  remote-repository-username:
    description: 'Username for the remote repository'
    required: false
  remote-repository-password:
    description: 'Password for the remote repository'
    required: false

runs:
  using: node20
  main: dist/index.js
